name: Deploy-To-Heroku

on:
  push:
    branches: [ develop ]

jobs:
  Quality-Check:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: production
    strategy:
      matrix:
        ruby-version: ['3.0.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    - name: Check Style and Performance
      run: bundle exec rake quality:rubocop
    
    - name: Check Code Smell
      run: bundle exec rake quality:reek
    
    - name: Run Tests
      run: |
           cp config/secrets_example.yml config/secrets.yml
           mkdir app/infrastructure/database/local
           bundle exec rake db:migrate RACK_ENV=test
           bundle exec rake spec

  Deploy:
    needs: [ Quality-Check ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: develop
